spring:
  datasource:
    name: test
    username: sa
    password:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
  jpa:
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
  batch:
    job:
      enabled: false
